eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.46:8761/eureka/
      
server:
  port: 8770
  
spring:
  application:
    name: one-service
    
feign: 
  hystrix: 
    enabled: true
